#! /bin/bash
# Copyright 2020 Alex Woroschilow (alex.woroschilow@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#set -ex

#=== From linuxdeploy-plugin-gtk.sh

gsettings get org.gnome.desktop.interface gtk-theme 2> /dev/null | grep -qi "dark" && GTK_THEME_VARIANT="dark" || GTK_THEME_VARIANT="light"
APPIMAGE_GTK_THEME="${APPIMAGE_GTK_THEME:-"Adwaita:$GTK_THEME_VARIANT"}" # Allow user to override theme (discouraged)
CACHEDIR="$(mktemp --tmpdir --directory .AppRun.XXXXXXXX)"

export APPDIR="${APPDIR:-"$(dirname "$(realpath "$0")")"}" # Workaround to run extracted AppImage

export GTK_DATA_PREFIX="$APPDIR"

export GTK_THEME="$APPIMAGE_GTK_THEME" # Custom themes are broken
export GDK_BACKEND=x11 # Crash with Wayland backend on Wayland
export XDG_DATA_DIRS="$APPDIR/usr/share:$XDG_DATA_DIRS" # g_get_system_data_dirs() from GLib
export GSETTINGS_SCHEMA_DIR="$APPDIR/usr/share/glib-2.0/schemas"

export GTK_EXE_PREFIX="$APPDIR/usr"

export GTK_PATH="$APPDIR/usr/lib/gtk-3.0"
export GTK_IM_MODULE_DIR="$APPDIR/usr/lib/gtk-3.0/3.0.0/immodules"
export GTK_IM_MODULE_FILE="$CACHEDIR/immodules.cache"
sed "s|/usr/lib/gtk-3.0|$APPDIR/usr/lib/gtk-3.0|g" "$APPDIR/usr/lib/gtk-3.0/3.0.0/immodules.cache" > "$GTK_IM_MODULE_FILE"
export GDK_PIXBUF_MODULEDIR="$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders"
export GDK_PIXBUF_MODULE_FILE="$CACHEDIR/loaders.cache"
sed "s|/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders|$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders|g" "$APPDIR/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache" > "$GDK_PIXBUF_MODULE_FILE"

#=== Specific to Geany there

export PATH=${PATH}:${APPDIR}/usr/bin:${APPDIR}/bin
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/usr/lib

export GEANY_PLUGINS_PATH="${APPDIR}/usr/lib/geany/:${APPDIR}/usr/local/lib/geany/"

GEANY_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/geany"

#Workaround for BinReloc mode: Update session.conf for active plugins defined in previous AppImage execution
#Note: since Geany 2.0, it is not anymore in config.conf
if [ -f "$GEANY_CONFIG_DIR/session.conf" ]; then
  sed -i "s|/tmp/.mount_Geany-[^/]*/|$APPDIR/|g" "$GEANY_CONFIG_DIR/session.conf"
fi

#shouldn't be necessary in BinReloc mode: cd ${APPDIR}/usr/share/geany
exec ${APPDIR}/usr/bin/geany "$@"
